# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Deploy to production

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    name: Build image
    runs-on: ubuntu-latest

  steps:
  # - name: Check out code
  #   uses: actions/checkout@v3
  - name: Debugging
    run: |
      pwd
      echo 'debugging!!'
      ls -l

  - name: Login to docker hub
    uses: actions-hub/docker/login@master
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

  # - name: Build :latest
  #   run: docker build -t ${GITHUB_REPOSITORY}:latest .

  # - name: Push to docker hub :latest
  #   uses: actions-hub/docker@master
  #   with:
  #     args: push ${GITHUB_REPOSITORY}:latest