# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Deploy to production

on:
  push:
    branches: [ "main" ]

jobs:

  deploy:
    name: Build Image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        go-version: 1.20
    - name: Debug
      run: |
        pwd
        ls -l

    - name: Login to docker hub
      uses: actions-hub/docker/login@master
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build :latest
      # run: docker build -t ${GITHUB_REPOSITORY}:latest .
      run: |
        docker build -t otirbid/simple-bank:latest .
        docker images


    - name: Push to docker hub :latest
      uses: actions-hub/docker@master
      with:
        args: push otirbid/simple-bank:latest
